# Generated by Django 6.1 on 2026-09-01 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=200)),
                ('event_type', models.CharField(default='Diagnostic Test', max_length=100)),
                ('event_date', models.CharField(max_length=50)),
                ('event_time', models.CharField(max_length=50)),
                ('status', models.CharField(default='Report Issued & Auto-Imported', max_length=100)),
                ('details', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
