# Generated by Django 5.2.17 on 2026-09-08 06:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InpatientAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_id', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('patient_name', models.CharField(max_length=150)),
                ('age', models.IntegerField(default=35)),
                ('gender', models.CharField(default='Male', max_length=20)),
                ('ward', models.CharField(default='General Male Ward', max_length=100)),
                ('bed_no', models.CharField(max_length=50)),
                ('attending_doctor', models.CharField(default='Consulting Physician', max_length=150)),
                ('diagnosis', models.CharField(max_length=255)),
                ('status', models.CharField(default='Admitted', max_length=50)),
                ('admission_date', models.DateField(default=django.utils.timezone.now)),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('discharge_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_admissions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_stays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-admission_date', '-created_at'],
            },
        ),
    ]
