# Generated by Django 5.2.17 on 2026-09-25 06:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inpatientadmission',
            name='admission_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
