# Generated by Django 5.2.17 on 2026-09-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_inpatientadmission_admission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inpatientadmission',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inpatientadmission',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
