# Generated by Django 5.2.17 on 2026-09-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_inpatientadmission_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inpatientadmission',
            name='attending_doctor',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='inpatientadmission',
            name='ward',
            field=models.CharField(default='General Ward', max_length=100),
        ),
    ]
