import '../../shared/models/timeline_event.dart';

class MockTimeline {
  static List<TimelineEvent> getTimelineEvents() {
    return [
      TimelineEvent(
        eventId: 'EVT001',
        patientId: 'PAT001',
        eventType: 'lab_report',
        title: 'Complete Blood Count (CBC)',
        description: 'Annual health checkup - All parameters normal',
        eventDate: '2024-01-15',
        facilityName: 'Dr. Lal PathLabs',
        doctorName: 'Dr. Priya Patel',
      ),
      TimelineEvent(
        eventId: 'EVT002',
        patientId: 'PAT001',
        eventType: 'lab_report',
        title: 'Lipid Profile',
        description: 'Elevated cholesterol levels detected',
        eventDate: '2024-01-15',
        facilityName: 'Dr. Lal PathLabs',
        doctorName: 'Dr. Priya Patel',
      ),
      TimelineEvent(
        eventId: 'EVT003',
        patientId: 'PAT001',
        eventType: 'prescription',
        title: 'Prescription - Annual Checkup',
        description: 'Vitamin D supplements prescribed',
        eventDate: '2024-01-15',
        facilityName: 'City General Hospital',
        doctorName: 'Dr. Priya Patel',
      ),
      TimelineEvent(
        eventId: 'EVT004',
        patientId: 'PAT001',
        eventType: 'surgery',
        title: 'Appendix Surgery',
        description: 'Laparoscopic appendectomy - Successful',
        eventDate: '2023-11-20',
        facilityName: 'Apollo Hospital',
        doctorName: 'Dr. Rajesh Kumar',
      ),
      TimelineEvent(
        eventId: 'EVT005',
        patientId: 'PAT001',
        eventType: 'discharge',
        title: 'Discharge from Hospital',
        description: 'Discharged after appendix surgery',
        eventDate: '2023-11-22',
        facilityName: 'Apollo Hospital',
        doctorName: 'Dr. Rajesh Kumar',
      ),
      TimelineEvent(
        eventId: 'EVT006',
        patientId: 'PAT001',
        eventType: 'imaging',
        title: 'X-Ray - Chest PA View',
        description: 'Routine chest X-ray - Normal',
        eventDate: '2023-08-10',
        facilityName: 'Diagno Labs',
        doctorName: 'Dr. Suresh Reddy',
      ),
      TimelineEvent(
        eventId: 'EVT007',
        patientId: 'PAT001',
        eventType: 'vaccination',
        title: 'COVID-19 Booster Dose',
        description: 'Received COVID-19 preventive booster dose',
        eventDate: '2023-06-15',
        facilityName: 'Primary Health Center',
        doctorName: 'Dr. Anita Desai',
      ),
      TimelineEvent(
        eventId: 'EVT008',
        patientId: 'PAT001',
        eventType: 'consultation',
        title: 'General Consultation',
        description: 'Consultation for viral fever - Antibiotics prescribed',
        eventDate: '2023-03-22',
        facilityName: 'City Clinic',
        doctorName: 'Dr. Vikram Singh',
      ),
      TimelineEvent(
        eventId: 'EVT009',
        patientId: 'PAT001',
        eventType: 'lab_report',
        title: 'Thyroid Function Test',
        description: 'Thyroid function normal',
        eventDate: '2023-11-20',
        facilityName: 'Apollo Hospital',
        doctorName: 'Dr. Rajesh Kumar',
      ),
      TimelineEvent(
        eventId: 'EVT010',
        patientId: 'PAT001',
        eventType: 'lab_report',
        title: 'Liver Function Test',
        description: 'Liver function tests within normal limits',
        eventDate: '2023-08-10',
        facilityName: 'Diagno Labs',
        doctorName: 'Dr. Suresh Reddy',
      ),
    ];
  }
}
