import '../../shared/models/lab_report.dart';

class MockReports {
  static List<LabReport> getReports() {
    return [
      LabReport(
        reportId: 'LAB001',
        patientId: 'PAT001',
        reportName: 'Complete Blood Count (CBC)',
        reportDate: '2024-01-15',
        facilityName: 'Dr. Lal PathLabs',
        doctorName: 'Dr. Priya Patel',
        testParameters: [
          TestParameter(
            parameterName: 'Hemoglobin',
            value: '14.5',
            unit: 'g/dL',
            referenceRange: '13.5-17.5',
            flag: 'normal',
          ),
          TestParameter(
            parameterName: 'WBC Count',
            value: '7.2',
            unit: 'x10^9/L',
            referenceRange: '4.5-11.0',
            flag: 'normal',
          ),
          TestParameter(
            parameterName: 'Platelet Count',
            value: '280',
            unit: 'x10^9/L',
            referenceRange: '150-400',
            flag: 'normal',
          ),
          TestParameter(
            parameterName: 'RBC Count',
            value: '4.8',
            unit: 'x10^12/L',
            referenceRange: '4.5-5.5',
            flag: 'normal',
          ),
        ],
        summary: 'All parameters within normal range. No abnormalities detected.',
        status: 'completed',
      ),
      LabReport(
        reportId: 'LAB002',
        patientId: 'PAT001',
        reportName: 'Lipid Profile',
        reportDate: '2024-01-15',
        facilityName: 'Dr. Lal PathLabs',
        doctorName: 'Dr. Priya Patel',
        testParameters: [
          TestParameter(
            parameterName: 'Total Cholesterol',
            value: '245',
            unit: 'mg/dL',
            referenceRange: '<200',
            flag: 'high',
          ),
          TestParameter(
            parameterName: 'HDL Cholesterol',
            value: '45',
            unit: 'mg/dL',
            referenceRange: '>40',
            flag: 'normal',
          ),
          TestParameter(
            parameterName: 'LDL Cholesterol',
            value: '160',
            unit: 'mg/dL',
            referenceRange: '<100',
            flag: 'high',
          ),
          TestParameter(
            parameterName: 'Triglycerides',
            value: '200',
            unit: 'mg/dL',
            referenceRange: '<150',
            flag: 'high',
          ),
        ],
        summary: 'Elevated cholesterol levels. Recommend dietary modifications and follow-up in 3 months.',
        status: 'completed',
      ),
      LabReport(
        reportId: 'LAB003',
        patientId: 'PAT001',
        reportName: 'Thyroid Function Test',
        reportDate: '2023-11-20',
        facilityName: 'Apollo Hospital',
        doctorName: 'Dr. Rajesh Kumar',
        testParameters: [
          TestParameter(
            parameterName: 'TSH',
            value: '2.5',
            unit: 'mIU/L',
            referenceRange: '0.4-4.0',
            flag: 'normal',
          ),
          TestParameter(
            parameterName: 'T3',
            value: '1.2',
            unit: 'ng/mL',
            referenceRange: '0.8-2.0',
            flag: 'normal',
          ),
          TestParameter(
            parameterName: 'T4',
            value: '1.0',
            unit: 'ng/dL',
            referenceRange: '0.7-1.8',
            flag: 'normal',
          ),
        ],
        summary: 'Thyroid function normal. No treatment required.',
        status: 'completed',
      ),
      LabReport(
        reportId: 'LAB004',
        patientId: 'PAT001',
        reportName: 'Liver Function Test',
        reportDate: '2023-08-10',
        facilityName: 'Diagno Labs',
        doctorName: 'Dr. Suresh Reddy',
        testParameters: [
          TestParameter(
            parameterName: 'SGOT/AST',
            value: '35',
            unit: 'U/L',
            referenceRange: '10-40',
            flag: 'normal',
          ),
          TestParameter(
            parameterName: 'SGPT/ALT',
            value: '32',
            unit: 'U/L',
            referenceRange: '10-40',
            flag: 'normal',
          ),
          TestParameter(
            parameterName: 'Bilirubin Total',
            value: '0.8',
            unit: 'mg/dL',
            referenceRange: '0.3-1.2',
            flag: 'normal',
          ),
          TestParameter(
            parameterName: 'Albumin',
            value: '4.2',
            unit: 'g/dL',
            referenceRange: '3.5-5.0',
            flag: 'normal',
          ),
        ],
        summary: 'Liver function tests within normal limits.',
        status: 'completed',
      ),
      LabReport(
        reportId: 'LAB005',
        patientId: 'PAT001',
        reportName: 'HbA1c',
        reportDate: '2023-06-15',
        facilityName: 'Primary Health Center',
        doctorName: 'Dr. Anita Desai',
        testParameters: [
          TestParameter(
            parameterName: 'HbA1c',
            value: '5.8',
            unit: '%',
            referenceRange: '4.0-5.7',
            flag: 'high',
          ),
        ],
        summary: 'Slightly elevated HbA1c. Recommend lifestyle modifications and re-test in 6 months.',
        status: 'completed',
      ),
    ];
  }
}
