# Generated by Django 6.1 on 2026-09-01 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(default='O +ve', max_length=10)),
                ('known_allergies', models.TextField(default='Penicillin, Sulfa Antibiotics')),
                ('chronic_conditions', models.TextField(default='Mild Asthma')),
                ('emergency_contact_name', models.CharField(default='Pooja Soni', max_length=150)),
                ('emergency_contact_phone', models.CharField(default='+91 98765 43210', max_length=20)),
                ('emergency_contact_relation', models.CharField(default='Kin / Spouse', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
