# Generated by Django 5.2.17 on 2026-09-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='current_medications',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
