# Generated by Django 5.2.17 on 2026-09-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('lab', 'Diagnostic Lab'), ('hospital', 'Hospital Care'), ('admin', 'System Administrator')], default='patient', max_length=20),
        ),
    ]
