# Generated by Django 5.2.17 on 2026-09-29 03:34

import django.db.models.functions.text
from django.db import migrations, models

def prepare_identity(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    users = list(User.objects.using(schema_editor.connection.alias).all())
    seen = set()
    for user in users:
        normalized = user.email.strip().lower()
        if normalized in seen:
            raise RuntimeError('Duplicate normalized emails found. Resolve identities manually before migrating.')
        seen.add(normalized)
    for user in users:
        user.email = user.email.strip().lower()
        aliases = {'lab_staff':'lab','hospital_staff':'hospital'}
        roles = {aliases.get(r,r) for r in [user.role, *(user.roles or [])]}
        user.pending_roles = sorted(roles & {'doctor','lab','hospital'})
        user.save(update_fields=['email','pending_roles'])
    # Codes issued before hashing must never remain reusable or readable.
    apps.get_model('accounts','EmailOTP').objects.using(schema_editor.connection.alias).update(is_used=True,otp='!expired-before-security-upgrade')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(default='login', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='professional_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='otp',
            field=models.CharField(max_length=128),
        ),
        migrations.RunPython(prepare_identity, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='accounts_email_case_unique'),
        ),
    ]
