# Generated by Django 5.2.17 on 2026-09-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailotp_attempts_emailotp_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
