# Generated by Django 5.2.17 on 2026-09-08 06:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('report_name', models.CharField(max_length=200)),
                ('category', models.CharField(default='Biochemistry', max_length=100)),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('facility_name', models.CharField(default='Diagnostic Lab', max_length=200)),
                ('doctor_name', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(default='Normal', max_length=50)),
                ('summary', models.TextField(blank=True, null=True)),
                ('file_url', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('record_type', models.CharField(max_length=50)),
                ('record_date', models.DateField(default=django.utils.timezone.now)),
                ('facility_name', models.CharField(blank=True, max_length=200, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('file_url', models.FileField(blank=True, null=True, upload_to='records/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-record_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_range', models.CharField(blank=True, max_length=100, null=True)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='reports.labreport')),
            ],
        ),
    ]
