# Generated by Django 6.1 on 2026-09-01 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(default='Blood Test', max_length=100)),
                ('category', models.CharField(default='Blood Tests', max_length=100)),
                ('provider', models.CharField(default='Dr. Lal PathLabs', max_length=200)),
                ('facility_type', models.CharField(default='Diagnostic Lab', max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('doctor_name', models.CharField(default='Dr. A. K. Sharma', max_length=150)),
                ('status', models.CharField(default='Verified & Synced', max_length=50)),
                ('source', models.CharField(default='Auto-Pulled via LIS API', max_length=150)),
                ('summary', models.TextField()),
                ('ai_explanation', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
