# Generated by Django 6.1 on 2026-09-01 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_id', models.CharField(max_length=50, unique=True)),
                ('doctor_name', models.CharField(max_length=150)),
                ('specialty', models.CharField(default='Cardiologist', max_length=100)),
                ('hospital_name', models.CharField(default='Max Healthcare Hospital', max_length=200)),
                ('purpose', models.CharField(default='Follow-up Heart Review', max_length=200)),
                ('scope', models.CharField(default='All Heart & ECG Reports', max_length=200)),
                ('expires_in', models.CharField(default='Valid for 23 hours', max_length=100)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Access Allowed'), ('REVOKED', 'Access Revoked by Patient'), ('EXPIRED', 'Access Expired')], default='ACTIVE', max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
